### ISSUE TITLE
ModuleNotFoundError: No module named 'clamp.deeptox'

### ISSUE THREAD

**Issue by MKCarter** [ml-jku/clamp#1]
Hi,

When running the code, it seems to fail on the `import clamp` command:

```
File ~/DD_tools/clamp/clamp/models/models.py:1
----> 1 from clamp.deeptox.models.perceptron import NetworkLayerNorm, MultilayerPerceptron
      3 from typing import List, Tuple
      5 import torch

ModuleNotFoundError: No module named 'clamp.deeptox'
```

Is this import correct, this is also the same in the `clamp/models/scaled.py` and ` clamp/models/gnn.py` scripts. 

Thanks

**Comment by MKCarter** [comment]
Modifying the import to:
`from clamp.models.perceptron import NetworkLayerNorm, MultilayerPerceptron`
Resolved this :)

**Comment by phseidl** [comment]
Hi, the code is still under development, particularly the model-training part.
I will update the import.
Once updated I will remove the disclaimer from the Readme.
Thanks for your interest in our paper.
