### ISSUE TITLE
`AttributeError: module 'clamp' has no attribute 'CLAMP'`

### ISSUE THREAD

**Issue by SimLif** [ml-jku/clamp#2]
`model = clamp.CLAMP(device='cpu')` causes error:  
`AttributeError: module 'clamp' has no attribute 'CLAMP'`

**Comment by phseidl** [comment]
Hi SimLif,
could you be more specific about the environment?
Was the package installed properly?
e.g. run ```pip install git+https://github.com/ml-jku/clamp```
An issue could be that the __init__.py is not called.
You can load CLAMP also via
```python
from clamp.models.pretrained import PretrainedCLAMP as CLAMP
```
