### ISSUE TITLE
Encountering an error while trying to run the encode_compound.py script for the PubChem23 dataset.

### ISSUE THREAD

**Issue by linhduongtuan** [ml-jku/clamp#5]
Dear Mr. Philipp Seidl,

I appreciate your keen work.
 I am encountering an error while trying to run the encode_compound.py script for the PubChem23 dataset. I am not sure if the error is due to the downloaded dataset or if there is a bug in the script. Can you please help me look at the attached file?

Thank you for your time and assistance.
Best regards,
Linh
![Untitled](https://github.com/ml-jku/clamp/assets/22388092/87b5a58f-4488-4ac3-9206-0e4ef7a6009d)

**Comment by phseidl** [comment]
Hi Linh,
thanks for your interest in our work.
There seems to be an error parsing one of the assay zip files.
Two things: We will add a try-catch block for invalid zip files, and additionally we will upload a preprocessed version of pubchem23 to make it more comparable.

Best, Philipp

**Comment by linhduongtuan** [comment]
Hi Philipp,
Thank you for your explanation.

I will waiting for your new release.

Best,
Linh

**Comment by phseidl** [comment]
Just pushed the changes, please inform us if that resolved the issue. 
Best, Philipp

**Comment by phseidl** [comment]
Just pushed the changes, please inform us if that resolved the issue.
Best, Philipp
