### ISSUE TITLE
other encoder implement

### ISSUE THREAD

**Issue by caocongfeng** [ml-jku/clamp#8]
Dear Mr. Philipp Seidl,

Thank you for your amazing work.

I would like to inquire if you could provide implementations for other encoders such as CDDD, MFBERT, Grover, sprsFP, MolT5-large, KV-PLM, and GAL 6.7B, which were mentioned in the paper section A.9.4 of your paper titled "MOLECULE- AND ASSAY-ENCODER ABLATION." I have attempted this myself, but your current code is challenging to adapt quickly. I am interested in conducting further research using these encoders and would greatly appreciate access to the corresponding code. I would also be honored to add you as a co-author on my paper.

Best regards,
Congfeng

**Comment by phseidl** [comment]
General Answer:
implementing other encoders requires specific environments e.g. for CDDD. 

The discussion has been continued offline.
